# Default properties
configFile:
credentialsDir:
testSuiteDescription:
testSuiteNamespace:
target:

# Logging
quarkus:
  log:
    level: INFO
    category:
      "com.intuit.karate":
        level: DEBUG
      "org.solid.testharness":
        level: INFO
