subjects: ./servers.ttl
sources:
  - https://raw.githubusercontent.com/solid/conformance-test-harness/main/example/solid-protocol-spec.ttl
  - https://raw.githubusercontent.com/solid/conformance-test-harness/main/example/web-access-control-spec.ttl
target: https://github.com/solid/conformance-test-harness/ess-compat
feature:
  mappings:
    - prefix: https://github.com/solid/conformance-test-harness/example
      path: ./example
    - prefix: https://raw.githubusercontent.com/solid/conformance-test-harness/main/example/solid
      path: example/solid
    - prefix: https://raw.githubusercontent.com/solid/conformance-test-harness/main/example/web
      path: example/web
