name: Solid Conformance Test Harness

on:
  push:
    branches:
      - main
    tags:
      - v[0-9]+.[0-9]+.[0-9]+

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Set up the Java environment
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      # Use a cache for the local Maven repository
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Build the software
      - name: Build with Maven
        run: mvn -B -ntp clean package

      # Deploy the docker container
      - name: Publish the Docker container
        run: |
          # Login to the docker repository
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}

          # Deploy the image
          mvn package -DskipTests -Dquarkus.container-image.image="docker.io/solidconformancetestbeta/conformance-test-harness" -Dquarkus.docker.dockerfile-jvm-path=src/main/docker/Dockerfile
        env:
          QUARKUS_CONTAINER_IMAGE_BUILD: "true"
          QUARKUS_CONTAINER_IMAGE_PUSH: "true"

